# Generated by Django 5.0.6 on 2024-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='Password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
