# Generated by Django 5.0.6 on 2024-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_students_info_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos/%y%m%d'),
        ),
    ]
